package dambi.accessingmongoumeak.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import dambi.accessingmongoumeak.model.Partida;
import dambi.accessingmongoumeak.model.PartidaRepository;

@RestController // This means that this class is a Controller baina @Controller bakarrik jarrita, PUT eta DELETEak ez dabiz
@RequestMapping(path = "/partidak") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called umeaRepository
				// Which is auto-generated by Spring, we will use it to handle the data
	private PartidaRepository partidarepository;

	
	@GetMapping(path = "/allPartida")
	public @ResponseBody Iterable<Partida> getAllPartidak() {
		// This returns a JSON or XML with the partidak
		System.out.println(partidarepository.findAll());
		return partidarepository.findAll();
	}


}